###
# Copyright (c) Mainflux
#
# Mainflux server is licensed under an Apache license, version 2.0.
# All rights not explicitly granted in the Apache license, version 2.0 are reserved.
# See the included LICENSE file for more details.
###

# HTTP
httpHost = "0.0.0.0"
httpPort = 9090

# MQTT
mqttHost = "localhost"
mqttPort = 1883

mqttTargetHost = "localhost"
mqttTargetPort = 1883

loraChannel = "mainflux/channel/12345678/"
